package View;

import Controller.ItemController;
import Model.Product;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ADMIN
 */
public class AccessoriesManagement extends javax.swing.JFrame {

    /**
     * Creates new form AccessoriesManagement
     */
    public AccessoriesManagement() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ac_id = new javax.swing.JTextField();
        ac_name = new javax.swing.JTextField();
        ac_status = new javax.swing.JTextField();
        ac_stock = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ac_price = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_ac = new javax.swing.JTable();
        edit_ac = new javax.swing.JButton();
        save_ac = new javax.swing.JButton();
        delete_ac = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        ac_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ac_idActionPerformed(evt);
            }
        });

        ac_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ac_nameActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Modern No. 20", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 51));
        jLabel4.setText("ID");

        jLabel6.setFont(new java.awt.Font("Modern No. 20", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 0, 51));
        jLabel6.setText("Price");

        jLabel7.setFont(new java.awt.Font("Modern No. 20", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 0, 51));
        jLabel7.setText("Name");

        jLabel8.setFont(new java.awt.Font("Modern No. 20", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 0, 51));
        jLabel8.setText("Status");

        jLabel9.setFont(new java.awt.Font("Modern No. 20", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 0, 51));
        jLabel9.setText("Stock");

        table_ac.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Status", "Stock", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table_ac.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                table_acAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(table_ac);

        edit_ac.setText("Edit");
        edit_ac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_acActionPerformed(evt);
            }
        });

        save_ac.setText("Save");
        save_ac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_acActionPerformed(evt);
            }
        });

        delete_ac.setText("Delete");
        delete_ac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_acActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Modern No. 20", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 51));
        jLabel5.setText("Accessories List");

        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(edit_ac)
                        .addGap(69, 69, 69)
                        .addComponent(save_ac)
                        .addGap(68, 68, 68)
                        .addComponent(delete_ac))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ac_id, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(ac_name, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ac_status, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ac_stock, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ac_price, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jButton4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 869, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 109, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ac_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ac_status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ac_stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ac_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(ac_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edit_ac)
                    .addComponent(save_ac)
                    .addComponent(delete_ac))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ac_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ac_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ac_idActionPerformed

    private void ac_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ac_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ac_nameActionPerformed

    private void edit_acActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_acActionPerformed
        // TODO add your handling code here:
        int selectedRow = table_ac.getSelectedRow();  // Get the selected row
    if (selectedRow != -1) {  // Check if a row is selected
        // Get the values from the selected row and set them in the text fields
        ac_id.setText(table_ac.getValueAt(selectedRow, 0).toString());
        ac_name.setText(table_ac.getValueAt(selectedRow, 1).toString());
        ac_stock.setText(table_ac.getValueAt(selectedRow, 2).toString());
        ac_status.setText(table_ac.getValueAt(selectedRow, 3).toString());
        ac_price.setText(table_ac.getValueAt(selectedRow, 4).toString());
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select a cat to edit.", "Selection Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_edit_acActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Manage_product manage_product = new Manage_product(); // Replace with your next JFrame class name
        manage_product.setVisible(true);
        this.dispose(); // Closes the current JFrame
    }//GEN-LAST:event_jButton4ActionPerformed

    private void save_acActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_acActionPerformed
            // TODO add your handling code here:
        String id = ac_id.getText();
        String name = ac_name.getText();
        String stock = ac_stock.getText();
        String status = ac_status.getText();
        String price = ac_price.getText();

        // Validate that all fields are filled
        if (id.isEmpty() || name.isEmpty() || stock.isEmpty() || status.isEmpty() || price.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please fill all fields.", "Input Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validate that the price is a valid number
        try {
            Double.valueOf(price);  // Try parsing the price as a double
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Price must be a valid number.", "Input Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Get the table model
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) table_ac.getModel();

        // Check if the ID already exists, but exclude the selected row
        int selectedRow = table_ac.getSelectedRow();
        for (int i = 0; i < model.getRowCount(); i++) {
            // Skip the row if it is the currently selected one (editing mode)
            if (i != selectedRow && model.getValueAt(i, 0).equals(id)) {
                javax.swing.JOptionPane.showMessageDialog(this, "ID already exists. Please choose a unique ID.", "Duplicate Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
        }

        if (selectedRow != -1) {
            // Update the existing row if a row is selected
            model.setValueAt(id, selectedRow, 0);
            model.setValueAt(name, selectedRow, 1);
            model.setValueAt(stock, selectedRow, 2);
            model.setValueAt(status, selectedRow, 3);
            model.setValueAt(price, selectedRow, 4);
        } else {
            // Add a new row if no row is selected
            model.addRow(new Object[]{id, name, stock, status, price});
        }
        
        double priceFixed = Double.parseDouble(price); 
        int stockFixed = Integer.parseInt(stock);
        Product product = new Product(name, priceFixed, stockFixed, status);
        ItemController.addProduct(product);

        // Clear the text fields after saving
        ac_id.setText("");
        ac_name.setText("");
        ac_stock.setText("");
        ac_status.setText("");
        ac_price.setText("");

        // Clear the selection on the table
        table_ac.clearSelection();

        // Show success message
        javax.swing.JOptionPane.showMessageDialog(this, "Accessory information saved successfully!", "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_save_acActionPerformed

    private void table_acAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_table_acAncestorAdded
        // TODO add your handling code here:
         javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) table_ac.getModel();

    // Check if the table is already populated to avoid duplicate rows
    if (model.getRowCount() > 0) {
        return;
    }
    model.addRow(new Object[]{"001", "Collar", "Available", "50", "15.99"});
    model.addRow(new Object[]{"002", "Leash", "Out of Stock", "0", "25.49"});
    model.addRow(new Object[]{"003", "Pet Bed", "Available", "30", "45.99"});
    model.addRow(new Object[]{"004", "Food Bowl", "Available", "100", "12.99"});
    model.addRow(new Object[]{"005", "Pet Toy", "Available", "75", "9.99"});    
                                 
    }//GEN-LAST:event_table_acAncestorAdded

    private void delete_acActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_acActionPerformed
        // TODO add your handling code here:
        int selectedRow = table_ac.getSelectedRow();
    
    if (selectedRow == -1) {
        // If no row is selected, show an error message
        javax.swing.JOptionPane.showMessageDialog(this, "Please select a row to delete.", "Delete Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Confirm deletion with the user
    int confirm = javax.swing.JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this entry?", "Delete Confirmation", javax.swing.JOptionPane.YES_NO_OPTION);

    if (confirm == javax.swing.JOptionPane.YES_OPTION) {
        // Delete the selected row
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) table_ac.getModel();
        model.removeRow(selectedRow);

        // Show success message
        javax.swing.JOptionPane.showMessageDialog(this, "Selected entry deleted successfully!", "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }
    }//GEN-LAST:event_delete_acActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccessoriesManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccessoriesManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccessoriesManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccessoriesManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AccessoriesManagement().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ac_id;
    private javax.swing.JTextField ac_name;
    private javax.swing.JTextField ac_price;
    private javax.swing.JTextField ac_status;
    private javax.swing.JTextField ac_stock;
    private javax.swing.JButton delete_ac;
    private javax.swing.JButton edit_ac;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton save_ac;
    private javax.swing.JTable table_ac;
    // End of variables declaration//GEN-END:variables
}
