package View;
import Controller.ItemController;
import Model.Pet;


/**
 *
 * @author ADMIN
 */
public class CatManagement extends javax.swing.JFrame {

    /**
     * Creates new form CatManagement
     */
    public CatManagement() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cat_id = new javax.swing.JTextField();
        cat_name = new javax.swing.JTextField();
        cat_breed = new javax.swing.JTextField();
        cat_species = new javax.swing.JTextField();
        cat_status = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cat_price = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_cat = new javax.swing.JTable();
        edit_cat = new javax.swing.JButton();
        save_cat = new javax.swing.JButton();
        delete_cat = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        cat_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cat_idActionPerformed(evt);
            }
        });

        cat_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cat_nameActionPerformed(evt);
            }
        });

        cat_breed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cat_breedActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Modern No. 20", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 51));
        jLabel4.setText("ID");

        jLabel5.setFont(new java.awt.Font("Modern No. 20", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 51));
        jLabel5.setText("Breed");

        jLabel6.setFont(new java.awt.Font("Modern No. 20", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 0, 51));
        jLabel6.setText("Price");

        jLabel7.setFont(new java.awt.Font("Modern No. 20", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 0, 51));
        jLabel7.setText("Name");

        jLabel8.setFont(new java.awt.Font("Modern No. 20", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 0, 51));
        jLabel8.setText("Status");

        jLabel9.setFont(new java.awt.Font("Modern No. 20", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 0, 51));
        jLabel9.setText("Species");

        table_cat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Breed", "Species", "Status", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table_cat.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                table_catAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(table_cat);

        edit_cat.setText("Edit");
        edit_cat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_catActionPerformed(evt);
            }
        });

        save_cat.setText("Save");
        save_cat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_catActionPerformed(evt);
            }
        });

        delete_cat.setText("Delete");
        delete_cat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_catActionPerformed(evt);
            }
        });

        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Modern No. 20", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 0, 51));
        jLabel10.setText("Cat List");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 869, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cat_id, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(cat_name, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cat_breed, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cat_species, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cat_status, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cat_price, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addComponent(edit_cat)
                        .addGap(69, 69, 69)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(save_cat)
                                .addGap(68, 68, 68)
                                .addComponent(delete_cat))
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(355, 355, 355))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jButton4)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jButton4)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cat_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cat_breed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cat_species, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cat_status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cat_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(cat_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edit_cat)
                    .addComponent(save_cat)
                    .addComponent(delete_cat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cat_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cat_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cat_idActionPerformed

    private void cat_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cat_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cat_nameActionPerformed

    private void cat_breedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cat_breedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cat_breedActionPerformed

    private void edit_catActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_catActionPerformed
        // TODO add your handling code here:
        int selectedRow = table_cat.getSelectedRow();  // Get the selected row
    if (selectedRow != -1) {  // Check if a row is selected
        // Get the values from the selected row and set them in the text fields
        cat_id.setText(table_cat.getValueAt(selectedRow, 0).toString());
        cat_name.setText(table_cat.getValueAt(selectedRow, 1).toString());
        cat_breed.setText(table_cat.getValueAt(selectedRow, 2).toString());
        cat_species.setText(table_cat.getValueAt(selectedRow, 3).toString());
        cat_status.setText(table_cat.getValueAt(selectedRow, 4).toString());
        cat_price.setText(table_cat.getValueAt(selectedRow, 5).toString());
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select a cat to edit.", "Selection Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_edit_catActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Manage_product manage_product = new Manage_product(); // Replace with your next JFrame class name
        manage_product.setVisible(true);
        this.dispose(); // Closes the current JFrame
    }//GEN-LAST:event_jButton4ActionPerformed

    private void save_catActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_catActionPerformed
        // TODO add your handling code here:
        String id = cat_id.getText();
        String name = cat_name.getText();
        String breed = cat_breed.getText();
        String species = cat_species.getText();
        String status = cat_status.getText();
        String price = cat_price.getText();

        // Validate that all fields are filled
        if (id.isEmpty() || name.isEmpty() || breed.isEmpty() || species.isEmpty() || status.isEmpty() || price.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please fill all fields.", "Input Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validate that the price is a valid number
        try {
            Double.valueOf(price);  // Try parsing the price as a double
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Price must be a valid number.", "Input Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Get the table model
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) table_cat.getModel();

        // Check if the ID already exists, but exclude the selected row
        int selectedRow = table_cat.getSelectedRow();
        for (int i = 0; i < model.getRowCount(); i++) {
            // Skip the row if it is the currently selected one (editing mode)
            if (i != selectedRow && model.getValueAt(i, 0).equals(id)) {
                javax.swing.JOptionPane.showMessageDialog(this, "ID already exists. Please choose a unique ID.", "Duplicate Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
        }

        if (selectedRow != -1) {
            // Update the existing row if a row is selected
            model.setValueAt(id, selectedRow, 0);
            model.setValueAt(name, selectedRow, 1);
            model.setValueAt(breed, selectedRow, 2);
            model.setValueAt(species, selectedRow, 3);
            model.setValueAt(status, selectedRow, 4);
            model.setValueAt(price, selectedRow, 5);
        } else {
            // Add a new row if no row is selected
            model.addRow(new Object[]{id, name, breed, species, status, price});
        }

        double priceFixed = Double.parseDouble(price); 
        Pet cat = new Pet(name, species, breed, priceFixed, status);
        ItemController.addCat(cat);
        
        // Clear the text fields after saving
        cat_id.setText("");
        cat_name.setText("");
        cat_breed.setText("");
        cat_species.setText("");
        cat_status.setText("");
        cat_price.setText("");

        // Clear the selection on the table
        table_cat.clearSelection();

        // Show success message
        javax.swing.JOptionPane.showMessageDialog(this, "Cat information saved successfully!", "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_save_catActionPerformed

    private void table_catAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_table_catAncestorAdded
        // TODO add your handling code here:
    javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) table_cat.getModel();

    // Check if the table is already populated to avoid duplicate rows
    if (model.getRowCount() > 0) {
        return;
    }
    model.addRow(new Object[]{"001", "Buddy", "Siamese", "Cat", "Available", "500"});
    model.addRow(new Object[]{"002", "Max", "Persian", "Cat", "Adopted", "600"});
    model.addRow(new Object[]{"003", "Bella", "Main Coon", "Cat", "Available", "550"});    
    }//GEN-LAST:event_table_catAncestorAdded

    private void delete_catActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_catActionPerformed
        // TODO add your handling code here:
        int selectedRow = table_cat.getSelectedRow();
    
    if (selectedRow == -1) {
        // If no row is selected, show an error message
        javax.swing.JOptionPane.showMessageDialog(this, "Please select a row to delete.", "Delete Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Confirm deletion with the user
    int confirm = javax.swing.JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this entry?", "Delete Confirmation", javax.swing.JOptionPane.YES_NO_OPTION);

    if (confirm == javax.swing.JOptionPane.YES_OPTION) {
        // Delete the selected row
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) table_cat.getModel();
        model.removeRow(selectedRow);

        // Show success message
        javax.swing.JOptionPane.showMessageDialog(this, "Selected entry deleted successfully!", "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }
    }//GEN-LAST:event_delete_catActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CatManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CatManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CatManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CatManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CatManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cat_breed;
    private javax.swing.JTextField cat_id;
    private javax.swing.JTextField cat_name;
    private javax.swing.JTextField cat_price;
    private javax.swing.JTextField cat_species;
    private javax.swing.JTextField cat_status;
    private javax.swing.JButton delete_cat;
    private javax.swing.JButton edit_cat;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton save_cat;
    private javax.swing.JTable table_cat;
    // End of variables declaration//GEN-END:variables
}
